const BACKEND_MATCHING_SERVICE_URL = process.env.URI_MATCH_SVC || 'http://localhost:7001';
const MATCHING_SERVICE_USER_RELATED = "/user";
const MATCHING_SERVICE_MATCH_RELATED = "/match";
const MATCHING_SERVICE_HEALTHCHECK = BACKEND_MATCHING_SERVICE_URL + "/healthcheck";
const BACKEND_MATCHING_SERVICE_END = "/end";
const BACKEND_MATCHING_SERVICE_TO_IDLE = "/toidle";
const BACKEND_QUESTION_SERVICE_GET_NEXT = "http://question-service:17001/question/next";

const EMBED_USERNAME = (name) => {
  console.log(`URL: ${BACKEND_MATCHING_SERVICE_URL}`);
  return BACKEND_MATCHING_SERVICE_URL + MATCHING_SERVICE_USER_RELATED + `/${name}`;
}

const EMBED_MATCHID = (id) => {
  console.log(`URL: ${BACKEND_MATCHING_SERVICE_URL}`);
  return BACKEND_MATCHING_SERVICE_URL + MATCHING_SERVICE_MATCH_RELATED + `/${id}`;
}

module.exports = {
  BACKEND_MATCHING_SERVICE_END,
  BACKEND_MATCHING_SERVICE_TO_IDLE,
  BACKEND_QUESTION_SERVICE_GET_NEXT,
  MATCHING_SERVICE_HEALTHCHECK,
  EMBED_USERNAME,
  EMBED_MATCHID
}

